sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script: make test
deploy:
  provider: pypi
  user: lyftpypi
  password:
    secure: kbp3cfgTRj709PmR9N+qfE721tPaOQk92cDstnATCGVB9G24B/D4QH1m8ZDTrnbCzyhIU2X80grBqdx85JEHmpkXp/pl36jREAlqAC8/D0nNYjLF0q1ZmCJYAEcY1Lupo6XnM5kEfmo0QNr784tfjl7APUf/J6hV6e6087KdTsQZfVs7CmdrXpzyrG3E27F2slm6EADHQLQGlBgMC//A4vKHdJMlD6W3seIeFGRaNeT4R+HZa6OcOioGBSo2vrZrlL2cnVI4ChWrzMjT6OK0hKxD3okfXbpFs6OdKlCQNbcNM7CXzzQRBSs77LajndyfhTK8gbKNr9xoZ+dO6qV7QiewOP6bJaRXaPn3SeDnWuWXdAxU1mrHNfeTmzeR901O76njbFlJSEsrgdkg67nc2Ignd3NefX5R49cLo3Kz9/193K4frWjN2li0OtGZfsvt0zrEEb/cFMMRvFseLipOliZ/I4BmOjURkcaDqeh+4j3MKUUCPRDkKi7CXicC0SDKF3+racBOCj2YO0UEZDywCVBy/wHTXlVrABD4jMDomquv1sYfNV3rgvOAHorMlJB0pMI3WYIAsztmPNFHV0odXatZZaJK5aL9Cy/1ELQWWCK4mwJjkX9NFm8hTymQG+C7pm4uTg7CZS92ud/8jtPwNsF7gDQ+9ajZMnAXsfY6rg4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: lyft/python-confidant-client
